apiVersion: v1
kind: ConfigMap
metadata:
  name: yopago-config
  namespace: yopago
data:
  KC_HOSTNAME: "localhost"
  KC_HOSTNAME_URL: "http://localhost:8082"
  YOPAGO_BACKEND_PUBLIC_URL: "http://localhost:8080/api"
