apiVersion: v1
kind: ConfigMap
metadata:
  name: yopago-config
  namespace: yopago
data:
  KC_HOSTNAME: "157.230.203.194"
  KC_HOSTNAME_URL: "http://157.230.203.194"
  YOPAGO_BACKEND_PUBLIC_URL: "http://157.230.203.194/api"
