apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yopago-ingress
  namespace: yopago
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.yopago.example.com
    - auth.yopago.example.com
    secretName: yopago-tls
  rules:
  - host: api.yopago.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yopago-api
            port:
              number: 8080
  - host: auth.yopago.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
