apiVersion: v1
kind: Namespace
metadata:
  name: yopago
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yopago-config
  namespace: yopago
data:
  POSTGRES_DB: "yopago"
  KEYCLOAK_REALM: "yopago"
  SPRING_PROFILES_ACTIVE: "prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: yopago-secrets
  namespace: yopago
type: Opaque
stringData:
  POSTGRES_USER: "yopago"
  POSTGRES_PASSWORD: "changeme"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "changeme"
